### ISSUE TITLE
about minimum number of mutations required for SomaticSignature

### ISSUE THREAD

**Issue by mortunco** [julian-gehring/SomaticSignatures#2]
Dear Julian,

Thank you for creating SomaticSignature, it is helping me a lot through my
masters degree.

I have a question about the package. so in "Deciphering signature of
mutational processes operative in human cancer paper", they mention about a
minimum number of mutations required for accurate prediction. I see that
you have not mention about a limiting parameter about this subject. Is
there a number which I should be cautious ?

Right now, I am comparing DHS regions mutation signature versus rest of the
mutations' signature in prostate cancer. My number in one of the samples
seems not too high and there I am having concerns about If the signature
that I see is a false positive or a noise.

Any idea would be very helpful,

Best regards,

Tunc.

**Comment by juliangehring** [comment]
It is fairly impossible to come up with a precise number for the minimal number of mutations that are required for a good analysis. This number will depend very much on the specific data set, especially the number of groups as well as the number and relative contributions of operative mutational signatures. How many variants do you typically have per sample in your data set?

**Comment by mortunco** [comment]
Hello,

Thank you for the rapid response !  I am investigating 196 Cancer patients mutation data ( ~ 80 k ) mutations, I compare this with TF proximity region mutations (~ 1k). Referring to the _Alexandrov, 2013_. They stated that ~480 will be enough for correct signature deciphering.

**Comment by juliangehring** [comment]
As far as I can see, the ~480 mutations refers to the specific setting of the Alexandrov paper, especially keeping in mind that the analysis was performed on manually curated variant calls. I would rather consider this as a lower bound for an analysis rather than a safe limit.

In your case with ~1000 mutations over 196 samples, you would have ~5 mutations per sample on average. I doubt that this is enough data for estimating meaningful mutational signatures.

**Comment by juliangehring** [comment]
Closing in lieu of https://support.bioconductor.org/p/94787/
