### ISSUE TITLE
Question regarding Normalization

### ISSUE THREAD

**Issue by fitbio** [julian-gehring/SomaticSignatures#7]
Hello, 

The tool is really interersting. I have a question. I want to normalize my whole exome samples to the genome level. I used KmerFrequency of your package. I followed the same example as listed in the vignette. But I am not sure what value to add for n. As the default seems to be n=1e4. Can you please tell how can I decide the "n" value ?

**Comment by juliangehring** [comment]
`n` defines the number of kmers that get sampled from the regions of interest, in order to compute the normalisation factors. The values of `n=1e4` is mentioned in the vignette as well: "As an example, we compute the frequency of 3-mers for the human toplevel chromosomes, based on a sample of 10'000 locations."

If you want to adjust signatures in whole-exome samples, you can simply use the precomputed normalisation factors that are also part of the package and mentioned in the next paragraph of the vignette: "The kmers dataset contains the estimated frequency of 3-mers across the human genome and exome."

In general, larger values for `n` yield more precise estimates, and a good estimate also depends on the size the genomic regions of interest. But from a practical perspective, using more than 10000 kmers will provide only small gains when considering the human genome.

If you are curious, you can also try different values for `n`, and see how they affect the precision of the normalisation factors.

As a side note, please use the [Bioconductor support site](http://support.bioconductor.org) instead of the github issues if you have questions (see also the "getting help" section in the vignette).

**Comment by fitbio** [comment]
Thank you :)
